### ISSUE TITLE
ランキングの分類の名称を「カテゴリ」から「ジャンル」に変更してほしい

### ISSUE THREAD

**Issue by yukiyalien** [yurafuca/nicotap#101]
**改善の内容**
お疲れ様です。要望を書かせていただきます。現在のニコニコ動画では、2019年6月26日に行われたランキングリニューアル等により、「カテゴリ」という概念は廃止され、ジャンルという概念が用いられております。そのため、ランキングでの"カテゴリ選択"という画面など、カテゴリという呼称が使われている文言を「ジャンル」ということばに直していただけると、ニコニコ動画本体との整合性も取れますし、ユーザーは迷わなくなると思います。

どうかご検討ください、よろしくお願いします:bow:

よろしかったら参考にしてください:
https://blog.nicovideo.jp/niconews/112002.html

**Comment by yurafuca** [comment]
ご要望ありがとうございます👐

そうでした．これまで "カテゴリ" とよばれていた分類の名前はランキングが整理されたとき "ジャンル" に変更されていたのをすっかり忘れていました……．

次回のバージョン v1.2.5 で名称をジャンルに変更します．
とっても助かります．ありがとうございます🌙

**Comment by yukiyalien** [comment]
ありがとうございます🙇🙇🙇🙇🙇

**Comment by yurafuca** [comment]
v1.2.5 でカテゴリをジャンルに変更しました．必要に応じてご自由に reopen してください．
