### ISSUE TITLE
視聴履歴のいつ見たかの時間の表示が「〜に投稿」になっている

### ISSUE THREAD

**Issue by ndxbn** [yurafuca/nicotap#41]
「〜に投稿」になっているけれど、ここに表示されている日時は視聴した時間なので、「〜に視聴」だと思います

![Screenshot_20190514-232104](https://user-images.githubusercontent.com/2140131/57705634-34d89e80-769f-11e9-9c7a-801c1b0196e8.png)

**Comment by yurafuca** [comment]
フィードバックありがとうございます✨
そうですね，ここは "～に視聴" へ変更します．

より踏み込んでいえば視聴時刻は些末な情報だと思われるので，かわりに再生数やコメント数を表示したいと思っています．一方で http://www.nicovideo.jp/api/videoviewhistory/list には再生数以外の statistics が含まれていないので，すぐに対応するのは難しそうです．

暫定的に "～に視聴" へ変更して，将来的にはなんらかの方法で上記の stats を表示できるといいと考えています．

**Comment by ndxbn** [comment]
なるほど、statistics 取ろうと思うと N+1問題になりそうで、難しそうですね…

個人的には、視聴履歴では視聴日時も見たいので、"代わりに"表示するのはちょっとなーって思います。

**Comment by yurafuca** [comment]
了解しました，視聴日時を残したまま stats を表示したいと思います😎

stats を取得する最も素朴で現実的な方法はおそらく https://www.nicovideo.jp/my/history のスクレイピングですね． http://www.nicovideo.jp/api/videoviewhistory/list では取得できる履歴の件数が 20 件でしたが，/my/history では 50 件になる副次的な効果もあります．パースが少々手間ですがやむを得ない気はします．

**Comment by yurafuca** [comment]
> /my/history では 50 件になる

プレミアム会員は 200 件になりますね．

**Comment by yurafuca** [comment]
お返事がたいへん遅れて申しわけありません 🙇

視聴日時を残したまま stats を表示しようと思っていたのですが，ひとまずは視聴日時だけを表示するようにしました．
'に投稿' は削除して日時だけを表示するようにしてあります．

この issue の不具合は解消されたのでひとまず close します．
不具合やご要望などがありましたらご自由に reopen してください．
