### ISSUE TITLE
再生中の動画を一時停止した後にシークバーを使用して動画の先頭まで戻すと、動画は停止した状態でシークバーが動き出す

### ISSUE THREAD

**Issue by drilldripper** [yurafuca/nicotap#56]
再生中の動画を一時停止した後にシークバーを使用して動画の先頭まで戻すと、動画は停止した状態でシークバーが動き出します。
動画は停止した状態ですが、コメントはシークバーの位置に対応して再生されるようです。

---
nicotap v0.0.16a
Pixel 3 (Android 9)

**Comment by yurafuca** [comment]
フィードバックありがとうございます👍

v1.0.0-alpha19 でこの問題に対処しました．
問題が再現する場合は気軽に reopen してください．
