### ISSUE TITLE
動画を一時停止した状態で画面が消えると、バックグラウンドで動画の再生が再開される

### ISSUE THREAD

**Issue by drilldripper** [yurafuca/nicotap#57]
動画を一時停止した状態で画面が消えると、動画が再開されます。
電源ボタンを使用した画面の消灯と、OS の自動消灯の両方で再現を確認しました。

---
nicotap v0.0.16a
Pixel 3 (Android 9)

**Comment by yurafuca** [comment]
フィードバックありがとうございます✨

* 電源ボタンを使用した画面の消灯
* OS の自動消灯

にくわえて，

* 一時停止した状態でホームボタンなどをタップして他の画面に遷移したとき

でもバックグラウンドで動画が再生されることを確認しました．v0.0.17a でこの問題に対処します．

**Comment by yurafuca** [comment]
v0.0.17a で対処しました．問題が再現する場合は reopen してください．
