### ISSUE TITLE
一時停止しても停止されずに無音で再生され続けることがある

### ISSUE THREAD

**Issue by ndxbn** [yurafuca/nicotap#64]
**バグの概要**

![Screenshot_20190614-093414](https://user-images.githubusercontent.com/2140131/59475666-a9ae1c80-8e87-11e9-8f30-47857412687a.png)

↑この画面で画面下半分の黒い部分をタップすると再生と一時停止がトグルされますが、再生中にタップしても体感で0.3秒くらい止まったあとに、映像とコメントの再生が再開されてしまいます。また、コメントだけ再生が再開されることもあります。音声は再生が再開されることはないようです。
再生の状態のアイコンは一時停止中になっています。シークバーは一時停止中には表示されないのでわかりづらいですが進んでいるようです。

**再現手順**
バグを再現させる手順を書いてください:

1. 適当に動画を開く
2. スクショの画面にする
3. 下半分の黒い部分をタップする
4. 0.3秒くらい停止された後に、音声以外（映像とコメント）が動き始める
  もしくは、コメントだけが動き始める。

**期待する挙動**

一時停止され、再生を再開するまで停止している

**スクリーンショット**

バグの説明に役立つスクリーンショットを用意できる場合，ここに追加してください．

**バグが発生した環境**
 - Device: Xperia XZ3
 - OS:  Android 9.0
 - Version: 0.0.17a

![Screenshot_20190614-094708](https://user-images.githubusercontent.com/2140131/59475974-6654ad80-8e89-11e9-9cab-50271f54ef04.png)

**補足 (optional)**

**Comment by ndxbn** [comment]
もしかしたら、 https://github.com/yurafuca/nicotap/issues/56 に似たような原因なのかも？しらんけど。
「シークバーは動いてて、コメントはシークバーの位置と合ってる」 あたり、同じような感じ。

**Comment by yurafuca** [comment]
フィードバックありがとうございます👍

v1.0.0-alpha19 でこの問題に対処しました．
あわせて，

> シークバーは一時停止中には表示されないのでわかりづらいですが進んでいるようです。

のようにシークバーの表示状態がトグルされてしまう問題にも対処しました．
問題が再現する場合は気軽に reopen してください．
