### ISSUE TITLE
2段階認証への対応

### ISSUE THREAD

**Issue by vandojapan** [yurafuca/nicotap#79]
**要望の概要**
2段階認証設定がされたアカウントへのログインができない

**要望のモチベーション**
ログインができない。ログインが必要な機能にアクセスできない。

**補足 (optional)**
この要望に関連する情報や画像がある場合，ここに追加してください．

**Comment by yurafuca** [comment]
ありがとうございます🙌

niconico における二段階認証を使用したログインの仕様がわかりました．
v1.1.0 として今晩リリースする予定です．

**Comment by yurafuca** [comment]
リリースしました．機能に不具合がある場合は reopen してください．
